apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  DB_HOST: database-1.co5uegiqknm0.us-east-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: admin  
  DB_USERNAME: admin
  DB_PASSWORD: N7#fQ2!XrP9

